### PR TITLE
Changes include to allow compilation with CUDA 11.0 on summit.

### LINKED ISSUE #29: Error compiling with CUDA 11.0
I have been using pykokkos-base successfully on summit with CUDA 11.4, however due to other issues (unrelated to pykokkos-base) I am reverting to CUDA 11.0. 

When I attempt to compile with CUDA 11.0 I get the following compiler errors:

```
[  9%] Building CXX object CMakeFiles/libpykokkos-core.dir/src/enumeration.cpp.o
pykokkos-base/src/enumeration.cpp(188): error: incomplete type is not allowed

pykokkos-base/src/enumeration.cpp(187): error: incomplete type is not allowed

pykokkos-base/src/enumeration.cpp(192): error: incomplete type is not allowed

pykokkos-base/src/enumeration.cpp(191): error: incomplete type is not allowed
```

and

```
kokkos/include/Kokkos_Concepts.hpp(410): error: static assertion failed with "template arguments must be memory spaces"
          detected during:
            instantiation of class "Kokkos::Impl::MemorySpaceAccess<DstMemorySpace, SrcMemorySpace> [with DstMemorySpace=Kokkos::HostSpace, SrcMemorySpace=Kokkos::CudaSpace]" 
pykokkos-base/src/available.cpp(101): here
            instantiation of class "memory_space_access<Tp, true> [with Tp=Kokkos::CudaSpace]" 
pykokkos-base/src/available.cpp(122): here
            instantiation of "auto get_host_accessible<SpecT,Idx,Tail...,<unnamed>>(size_t, std::index_sequence<Idx, Tail...>) [with SpecT=MemorySpaceSpecialization, Idx=1UL, Tail=<2UL, 3UL, 4UL, 5UL, 6UL, 7UL, 8UL, 9UL>, <unnamed>=0]" 

... and more of the same
```

Using gcc/9.3.0, Kokkos 3.5.00

### PR DESCRIPTION
**Pull request by kaschau**
Fixes #29

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
@jrmadsen

I encountered the matching issue, and this also fixes the compilation error for me with newer Kokkos/CUDA versions.

Are the CI failures real here? Do you need help fixing them? If so, any suggestions on where to start on those?

**Comment by jrmadsen** [comment]
@tylerjereddy When #33 gets merged, pull in those changes and push them

**Comment by jrmadsen** [comment]
The changes in this PR are included in #33
