### ISSUE TITLE
Error compiling with CUDA 11.0

### ISSUE THREAD

**Issue by kaschau** [kokkos/pykokkos-base#29]
I have been using pykokkos-base successfully on summit with CUDA 11.4, however due to other issues (unrelated to pykokkos-base) I am reverting to CUDA 11.0. 

When I attempt to compile with CUDA 11.0 I get the following compiler errors:

```
[  9%] Building CXX object CMakeFiles/libpykokkos-core.dir/src/enumeration.cpp.o
pykokkos-base/src/enumeration.cpp(188): error: incomplete type is not allowed

pykokkos-base/src/enumeration.cpp(187): error: incomplete type is not allowed

pykokkos-base/src/enumeration.cpp(192): error: incomplete type is not allowed

pykokkos-base/src/enumeration.cpp(191): error: incomplete type is not allowed
```

and

```
kokkos/include/Kokkos_Concepts.hpp(410): error: static assertion failed with "template arguments must be memory spaces"
          detected during:
            instantiation of class "Kokkos::Impl::MemorySpaceAccess<DstMemorySpace, SrcMemorySpace> [with DstMemorySpace=Kokkos::HostSpace, SrcMemorySpace=Kokkos::CudaSpace]" 
pykokkos-base/src/available.cpp(101): here
            instantiation of class "memory_space_access<Tp, true> [with Tp=Kokkos::CudaSpace]" 
pykokkos-base/src/available.cpp(122): here
            instantiation of "auto get_host_accessible<SpecT,Idx,Tail...,<unnamed>>(size_t, std::index_sequence<Idx, Tail...>) [with SpecT=MemorySpaceSpecialization, Idx=1UL, Tail=<2UL, 3UL, 4UL, 5UL, 6UL, 7UL, 8UL, 9UL>, <unnamed>=0]" 

... and more of the same
```

Using gcc/9.3.0, Kokkos 3.5.00

**Comment by jrmadsen** [comment]
@crtrott @dalg24 This looks like a Kokkos-Core bug. The template arguments _are_ memory spaces: `DstMemorySpace=Kokkos::HostSpace, SrcMemorySpace=Kokkos::CudaSpace`

**Comment by jrmadsen** [comment]
@kaschau Do you have these errors with other versions of Kokkos? I'm wondering if the incomplete type is due to some header restructuring or something and the rest of the errors are just a by-product of this. Is the incomplete type error the very first error you see?

**Comment by jrmadsen** [comment]
@kaschau An easy way to check compilation against a known working version of Kokkos would be to enable `-DENABLE_INTERNAL_KOKKOS=ON` in CMake. This should hopefully tell us whether this is actually something dependent on the CUDA version or the Kokkos version.

**Comment by kaschau** [comment]
> @kaschau Do you have these errors with other versions of Kokkos? I'm wondering if the incomplete type is due to some header restructuring or something and the rest of the errors are just a by-product of this. Is the incomplete type error the very first error you see?

@jrmadsen The incomplete type error is the first error I see. But that's just due to cmake picking up enumerate.cpp first. If I slap #Include "Kokkos_Core.hpp" on top of enumerate.cpp I still get the second error. (which is also appeased with including Kokkos_Core)

**Comment by kaschau** [comment]
> @kaschau An easy way to check compilation against a known working version of Kokkos would be to enable `-DENABLE_INTERNAL_KOKKOS=ON` in CMake. This should hopefully tell us whether this is actually something dependent on the CUDA version or the Kokkos version.

@jrmadsen Unfortunately compiling with internal kokkos = on consumes too many resources on the head node and gets killed. I can try and revert to an earlier release of Kokkos.

**Comment by kaschau** [comment]
Reverting to kokkos 3.3.00, CUDA 11.0 yields a similar, but different error.

```
[  2%] Building CXX object CMakeFiles/libpykokkos-core.dir/src/libpykokkos.cpp.o
/ccs/home/kschau/software/kokkos/include/KokkosExp_InterOp.hpp(92): error: filter_type_list_t is not a template

/ccs/home/kschau/software/kokkos/include/KokkosExp_InterOp.hpp(92): error: identifier "is_default_memory_trait" is undefined

2 errors detected in the compilation of "/ccs/home/kschau/software/sources/pykokkos-base/src/libpykokkos.cpp".
make[2]: *** [CMakeFiles/libpykokkos-core.dir/build.make:76: CMakeFiles/libpykokkos-core.dir/src/libpykokkos.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:162: CMakeFiles/libpykokkos-core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by jrmadsen** [comment]
> Unfortunately compiling with internal kokkos = on consumes too many resources on the head node and gets killed.

Are you building via `python setup.py install`? You can probably fix this by using fewer processors, e.g. `python setup.py install -j 4 <etc.>`

**Comment by jrmadsen** [comment]
> The incomplete type error is the first error I see. But that's just due to cmake picking up enumerate.cpp first. If I slap #Include "Kokkos_Core.hpp" on top of enumerate.cpp I still get the second error. (which is also appeased with including Kokkos_Core)

Try changing:

https://github.com/kokkos/pykokkos-base/blob/a195eaaaf0cef83c9b98eb317a4cdb0bb4bcf4f5/include/fwd.hpp#L50

to

```cpp
#include <Kokkos_Core.hpp>
```

and if that works, create a PR.
